import { Montserrat } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/frontend/redux/reduxProvider.js";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "700"],
});

export const metadata = {
  title: "Kokoma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
